baseURL: https://nandicre2.github.io/
copyright: "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
enableRobotsTXT: true
languageCode: fr-fr
title: Le blog de Nandicre
theme: "WonderMod"

markup:
   highlight:
        style: dracula
        noClasses: false
        guessSyntax: true
